/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Comentario;
import modelo.Publicacion;
import modelo.Usuario;
import persistencia.PublicacionDAO;
import persistencia.UsuarioDAO;

/**
 *
 * @author ASUS-VASQUEZ
 */
public final class PublicacionVista extends javax.swing.JFrame {

    private modelo.Publicacion publicacion;
    private final Publicacion publicacionMostrada;
    private final Usuario usuarioLogueado;

    /**
     * Creates new form PublicacionVista
     *
     * @param publicacion
     * @param usuario
     */
    public PublicacionVista(modelo.Publicacion publicacion, modelo.Usuario usuario) {
        this.usuarioLogueado = usuario;
        this.publicacion = publicacion;
        this.publicacionMostrada = publicacion;
        initComponents();
        actualizarVista();

        // Aquí puedes añadir el código para mostrar los datos en la ventana
        this.setTitle("Publicación de " + publicacion.getUsuario().getNombre());
        // ej: textAreaContenido.setText(publicacion.getContenido());
    }

    private void actualizarVista() {
        // Esta parte está bien
        lblNombreAutor.setText("Publicación de: " + publicacion.getUsuario().getNombre());
        txtAreaContenido.setText(publicacion.getContenido());

        StringBuilder textoComentarios = new StringBuilder();
        if (publicacion.getComentarios() != null) {

            // --- CORRECCIÓN AQUÍ ---
            // Se recorre cada comentario individual usando la variable 'c'
            for (Comentario c : publicacion.getComentarios()) {
                // Asumiendo que la clase Comentario tiene getAutor() y getTexto()
                textoComentarios.append(c.getAutor().getNombre()) // Usa 'c' minúscula
                        .append(": ")
                        .append(c.getTexto()) // Usa 'c' minúscula
                        .append("\n");
            }
        }
        txtAreaComentarios.setText(textoComentarios.toString());

    }

    public void mostrarVentanaPublicacion(String emailUsuario) {
        // 1. Crear instancias de los DAO
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        PublicacionDAO publicacionDAO = new PublicacionDAO();

        try {
            // 2. Usar el email que se pasa como parámetro
            Usuario usuarioLogueado = usuarioDAO.buscarPorCorreo(emailUsuario);

            // CORRECCIÓN: Se usa obtenerPublicacionSimple
            Publicacion publicacionAMostrar = publicacionDAO.obtenerPublicacionSimple();

            // 3. Verificación para evitar errores si algo no se encuentra
            if (usuarioLogueado == null || publicacionAMostrar == null) {
                System.err.println("Error: No se pudieron cargar los datos de ejemplo desde el DAO.");
                return;
            }

            // 4. Crear y mostrar la Vista
            PublicacionVista vistaPublicacion = new PublicacionVista(publicacionAMostrar, usuarioLogueado);
            vistaPublicacion.setVisible(true);

        } catch (java.sql.SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaContenido = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaComentarios = new javax.swing.JTextArea();
        txtNuevoComentario = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaContenido.setEditable(false);
        txtAreaContenido.setColumns(20);
        txtAreaContenido.setRows(5);
        jScrollPane1.setViewportView(txtAreaContenido);

        txtAreaComentarios.setEditable(false);
        txtAreaComentarios.setColumns(20);
        txtAreaComentarios.setRows(5);
        jScrollPane2.setViewportView(txtAreaComentarios);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNuevoComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComentar)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComentar)
                    .addComponent(txtNuevoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        String texto = txtNuevoComentario.getText().trim();
        if (!texto.isEmpty()) {
            Comentario nuevoComentario = new Comentario(this.usuarioLogueado, texto);

            // Llama al método sobre el objeto, no sobre la clase
            this.publicacionMostrada.agregarComentario(nuevoComentario);

            txtNuevoComentario.setText("");
            actualizarVista();
        }
    }//GEN-LAST:event_btnComentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreAutor;
    private javax.swing.JTextArea txtAreaComentarios;
    private javax.swing.JTextArea txtAreaContenido;
    private javax.swing.JTextField txtNuevoComentario;
    // End of variables declaration//GEN-END:variables
}
