/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Comentario;
import modelo.Publicacion;
import modelo.Usuario;

/**
 *
 * @author ASUS-VASQUEZ
 */
public class PublicacionVista extends javax.swing.JFrame {

    private Publicacion publicacion;

    /**
     * Creates new form PublicacionVista
     *
     * @param publicacion
     */
    public PublicacionVista(Publicacion publicacion) {
        initComponents(); // Método de NetBeans
        this.publicacion = publicacion;
        this.setLocationRelativeTo(null); // Centrar ventana
        actualizarVista(); // Llenar la UI con datos    
    }

    public void actualizarVista() {
        lblAutor.setText("Publicación de: " + publicacion.getAutor().getNombreUsuario());
        txtAreaPublicacion.setText(publicacion.getTextoPublicacion());

        StringBuilder textoComentarios = new StringBuilder();
        // Este bucle ahora funciona porque ArrayListPersonalizado es Iterable
        for (Comentario c : publicacion.getComentarios()) {
            textoComentarios.append(c.toString()).append("\n");
        }
        txtAreaComentarios.setText(textoComentarios.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPublicacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaComentarios = new javax.swing.JTextArea();
        txtNuevoComentario = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAutor.setText("Autor");

        txtAreaPublicacion.setEditable(false);
        txtAreaPublicacion.setColumns(20);
        txtAreaPublicacion.setRows(5);
        jScrollPane1.setViewportView(txtAreaPublicacion);

        txtAreaComentarios.setEditable(false);
        txtAreaComentarios.setColumns(20);
        txtAreaComentarios.setRows(5);
        jScrollPane2.setViewportView(txtAreaComentarios);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNuevoComentario)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnComentar)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblAutor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComentar))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        String texto = txtNuevoComentario.getText();
        if (texto != null && !texto.trim().isEmpty()) {
            // En una app real, aquí iría el usuario que ha iniciado sesión
            Usuario autorComentario = publicacion.getAutor();
            Comentario nuevoComentario = new Comentario(autorComentario, texto);

            publicacion.agregarComentario(nuevoComentario); // Actualiza el modelo
            txtNuevoComentario.setText(""); // Limpia el campo de texto
            actualizarVista(); // Refresca la UI
        }
    }//GEN-LAST:event_btnComentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JTextArea txtAreaComentarios;
    private javax.swing.JTextArea txtAreaPublicacion;
    private javax.swing.JTextField txtNuevoComentario;
    // End of variables declaration//GEN-END:variables
}
