/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Comentario;
import modelo.Publicacion;
import modelo.Usuario;

/**
 *
 * @author ASUS-VASQUEZ
 */
public class PublicacionVista extends javax.swing.JFrame {

    private Publicacion publicacion;
    private Usuario usuarioLogueado;

    /**
     * Creates new form PublicacionVista
     *
     * @param publicacion
     */
    public PublicacionVista(Publicacion publicacion) {
        initComponents(); // Método de NetBeans
        this.publicacion = publicacion;
        this.usuarioLogueado = usuarioLogueado;
        this.setLocationRelativeTo(null); // Centrar ventana
        actualizarVista(); // Llenar la UI con datos    
    }

    public void actualizarVista() {
        
        lblNombreAutor.setText("Publicación de: " + publicacion.getAutor().getNombreUsuario());

        txtAreaPublicacion.setText(publicacion.getTextoPublicacion());

        StringBuilder textoComentarios = new StringBuilder();
        // Este bucle ahora funciona porque ArrayListPersonalizado es Iterable
        for (Comentario c : publicacion.getComentarios()) {
            textoComentarios.append(c.toString()).append("\n");
        }
        txtAreaComentarios.setText(textoComentarios.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPublicacion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaComentarios = new javax.swing.JTextArea();
        txtNuevoComentario = new javax.swing.JTextField();
        btnComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaPublicacion.setEditable(false);
        txtAreaPublicacion.setColumns(20);
        txtAreaPublicacion.setRows(5);
        jScrollPane1.setViewportView(txtAreaPublicacion);

        txtAreaComentarios.setEditable(false);
        txtAreaComentarios.setColumns(20);
        txtAreaComentarios.setRows(5);
        jScrollPane2.setViewportView(txtAreaComentarios);

        btnComentar.setText("Comentar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNuevoComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComentar)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComentar)
                    .addComponent(txtNuevoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        String texto = txtNuevoComentario.getText();
        if (texto != null && !texto.trim().isEmpty()) {
            // 3. USA EL USUARIO LOGUEADO EN LUGAR DE UNO SIMULADO
            Comentario nuevoComentario = new Comentario(this.usuarioLogueado, texto);
            
            publicacion.agregarComentario(nuevoComentario);
            txtNuevoComentario.setText("");
            actualizarVista();
        }
    }//GEN-LAST:event_btnComentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreAutor;
    private javax.swing.JTextArea txtAreaComentarios;
    private javax.swing.JTextArea txtAreaPublicacion;
    private javax.swing.JTextField txtNuevoComentario;
    // End of variables declaration//GEN-END:variables
}
