/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Recurso;
import modelo.Usuario;
import servicios.ServicioRecursos;

public class VentanaRecursos extends javax.swing.JFrame {

    private final Usuario usuarioLogueado;
    private DefaultTableModel tableModel;

    public VentanaRecursos(Usuario usuario) {
        this.usuarioLogueado = usuario;
        initComponents();

        this.setTitle("Recursos Educativos");
        this.setLocationRelativeTo(null);

        inicializarTabla();
        cargarRecursos();
    }

    private void inicializarTabla() {
        
        tableModel = new DefaultTableModel() {
        @Override
                public boolean isCellEditable(int row, int column) {
        return false;
    }
    };
        tableModel.addColumn("Título");
        tableModel.addColumn("Tipo");
        tableModel.addColumn("Subido por");
        tableModel.addColumn("Fecha");
        tablaRecursos.setModel(tableModel);
    }

    private void cargarRecursos() {
        // Limpiar filas anteriores
        tableModel.setRowCount(0);

        ServicioRecursos servicio = new ServicioRecursos();
        try {
            java.util.List<Recurso> recursos = servicio.obtenerTodosLosRecursos();
            for (Recurso r : recursos) {
                Object[] fila = new Object[4];
                fila[0] = r.getTitulo();
                fila[1] = r.getTipoArchivo();
                fila[2] = r.getUsuario().getNombre() + " " + r.getUsuario().getApellido();
                fila[3] = r.getFechaPublicacion().toString();
                tableModel.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar recursos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRecursos = new javax.swing.JTable();
        botonSubir = new javax.swing.JButton();
        JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaRecursos);

        jScrollPane1.setViewportView(jScrollPane2);

        botonSubir.setText("Subir Nuevo Recurso");
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });

        JButton.setText("Cerrar");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(botonSubir)
                        .addGap(81, 81, 81)
                        .addComponent(JButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSubir)
                    .addComponent(JButton))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
          JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            
            String titulo = JOptionPane.showInputDialog(this, "Introduce un título para el recurso:");
            if (titulo == null || titulo.trim().isEmpty()) {
                return; // El usuario canceló o no escribió nada
            }

            try {
                // Crear una carpeta para guardar los recursos si no existe
                Path directorioDestino = Paths.get("recursos_compartidos");
                if (!Files.exists(directorioDestino)) {
                    Files.createDirectories(directorioDestino);
                }

                // Copiar el archivo al directorio del proyecto
                Path destino = directorioDestino.resolve(archivoSeleccionado.getName());
                Files.copy(archivoSeleccionado.toPath(), destino, StandardCopyOption.REPLACE_EXISTING);

                // Guardar la información en la base de datos
                ServicioRecursos servicio = new ServicioRecursos();
                String tipo = archivoSeleccionado.getName().substring(archivoSeleccionado.getName().lastIndexOf(".") + 1);
                
                servicio.subirRecurso(titulo, "", archivoSeleccionado.getName(), tipo, this.usuarioLogueado);
                
                JOptionPane.showMessageDialog(this, "Recurso subido con éxito.");
                cargarRecursos(); // Actualizar la tabla

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al subir el archivo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_botonSubirActionPerformed

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        this.dispose(); // Cierra únicamente esta ventana
    }//GEN-LAST:event_JButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton;
    private javax.swing.JButton botonSubir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaRecursos;
    // End of variables declaration//GEN-END:variables
}
