/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Usuario;
import servicios.ServiciosConexiones;
import servicios.ServiciosUsuarios;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import servicios.ServiciosUsuarios;

public class VentanaBuscarUsuarios extends javax.swing.JFrame {

    private final Usuario usuarioLogueado;
    private java.util.List<Usuario> listaDeUsuariosCompleta;
    private DefaultListModel<String> listModel;

    public VentanaBuscarUsuarios(Usuario usuario) {

        this.usuarioLogueado = usuario;
        this.listModel = new DefaultListModel<>();
        initComponents();

        this.setTitle("Buscar Usuarios");
        this.setLocationRelativeTo(null);
        listaUsuarios.setModel(listModel);

        cargarUsuarios();
    }

    
     private void cargarUsuarios() {
        ServiciosUsuarios serviciosUsuarios = new ServiciosUsuarios();
        try {
            this.listaDeUsuariosCompleta = serviciosUsuarios.obtenerTodosLosUsuarios(this.usuarioLogueado);
            listModel.clear();
            for (Usuario u : this.listaDeUsuariosCompleta) {
                listModel.addElement(u.getNombre() + " " + u.getApellido() + " - " + u.getCarrera());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        botonEnviarSolicitud = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listaUsuarios);

        botonEnviarSolicitud.setText("Enviar Solicitud");
        botonEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarSolicitudActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEnviarSolicitud)
                        .addGap(127, 127, 127)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnviarSolicitud)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarSolicitudActionPerformed
        int indiceSeleccionado = listaUsuarios.getSelectedIndex();

    // Verificar que un usuario haya sido seleccionado de la lista
    if (indiceSeleccionado != -1) {
        try {
            // Obtener el objeto Usuario completo de la lista de respaldo
            Usuario destinatario = this.listaDeUsuariosCompleta.get(indiceSeleccionado);

            // Llamar al servicio de conexiones para enviar la solicitud
            ServiciosConexiones servicioConexiones = new ServiciosConexiones();
            servicioConexiones.enviarSolicitud(this.usuarioLogueado, destinatario);

            JOptionPane.showMessageDialog(this, "Solicitud de conexión enviada a " + destinatario.getNombre());

        } catch (Exception e) {
            // Manejar posibles errores, como enviar una solicitud duplicada
            if (e.getMessage().contains("duplicada")) {
                JOptionPane.showMessageDialog(this, "Ya has enviado una solicitud a este usuario.", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al enviar la solicitud: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario de la lista.");
    }
        
        
        
    }//GEN-LAST:event_botonEnviarSolicitudActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviarSolicitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
