/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Recurso;
import modelo.Usuario;
import servicios.ServicioRecursos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaRecursosPrivados extends javax.swing.JFrame {

    private final Usuario usuarioLogueado;
    private DefaultTableModel tableModel;

    public VentanaRecursosPrivados(Usuario usuario) {
        this.usuarioLogueado = usuario;
        initComponents();
        this.setTitle("Mis Recursos Privados");
        this.setLocationRelativeTo(null);
        inicializarTabla();
        cargarRecursosPrivados();
    }

    private void cargarRecursosPrivados() {

        tableModel.setRowCount(0);
        ServicioRecursos servicio = new ServicioRecursos();
        try {
            java.util.List<Recurso> recursos = servicio.obtenerRecursosPrivados(this.usuarioLogueado);
            if (recursos.isEmpty()) {
                 tableModel.addRow(new Object[]{"No tienes recursos privados", "", ""});
            } else {
                for (Recurso r : recursos) {
                    Object[] fila = new Object[3];
                    fila[0] = r.getTitulo();
                    fila[1] = r.getTipoArchivo();
                    fila[2] = r.getFechaPublicacion().toString();
                    tableModel.addRow(fila);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar recursos privados: " + e.getMessage());
        }
    }

    private void inicializarTabla() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableModel.addColumn("Título");
        tableModel.addColumn("Tipo");
        tableModel.addColumn("Fecha");
        tablaRecursosPrivados.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRecursosPrivados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaRecursosPrivados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRecursosPrivados);

        jButton1.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRecursosPrivados;
    // End of variables declaration//GEN-END:variables
}
